In [62]:
import numpy as np
import pandas as pd

In [63]:
wine = pd.read_csv(r"C:\Users\Kajal\Desktop\dataset work November\dataset label encoding\wine_Quality_balanced.csv")
wine

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0         1            7.0              0.27         0.36            20.7   
1         1            6.3              0.30         0.34             1.6   
2         1            8.1              0.28         0.40             6.9   
3         1            7.2              0.23         0.32             8.5   
4         1            7.2              0.23         0.32             8.5   
...     ...            ...               ...          ...             ...   
19847     1            6.9              0.36         0.34             4.2   
19848     1            6.6              0.36         0.29             1.6   
19849     1            7.4              0.24         0.36             2.0   
19850     1            6.6              0.36         0.29             1.6   
19851     1            6.9              0.36         0.34             4.2   

       chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0          0.045                 45.0                 170.0  1.00100  3.00   
1          0.049                 14.0                 132.0  0.99400  3.30   
2          0.050                 30.0                  97.0  0.99510  3.26   
3          0.058                 47.0                 186.0  0.99560  3.19   
4          0.058                 47.0                 186.0  0.99560  3.19   
...          ...                  ...                   ...      ...   ...   
19847      0.018                 57.0                 119.0  0.98980  3.28   
19848      0.021                 24.0                  85.0  0.98965  3.41   
19849      0.031                 27.0                 139.0  0.99055  3.28   
19850      0.021                 24.0                  85.0  0.98965  3.41   
19851      0.018                 57.0                 119.0  0.98980  3.28   

       sulphates  alcohol  quality  
0           0.45      8.8        6  
1           0.49      9.5        6  
2           0.44     10.1        6  
3           0.40      9.9        6  
4           0.40      9.9        6  
...          ...      ...      ...  
19847       0.36     12.7        9  
19848       0.61     12.4        9  
19849       0.48     12.5        9  
19850       0.61     12.4        9  
19851       0.36     12.7        9  

[19852 rows x 13 columns]

In [64]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19852 entries, 0 to 19851
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  19852 non-null  int64  
 1   fixed acidity         19852 non-null  float64
 2   volatile acidity      19852 non-null  float64
 3   citric acid           19852 non-null  float64
 4   residual sugar        19852 non-null  float64
 5   chlorides             19852 non-null  float64
 6   free sulfur dioxide   19852 non-null  float64
 7   total sulfur dioxide  19852 non-null  float64
 8   density               19852 non-null  float64
 9   pH                    19852 non-null  float64
 10  sulphates             19852 non-null  float64
 11  alcohol               19852 non-null  float64
 12  quality               19852 non-null  int64  
dtypes: float64(11), int64(2)
memory usage: 2.0 MB


In [65]:
wine.describe()

type  fixed acidity  volatile acidity   citric acid  \
count  19852.000000   19852.000000      19852.000000  19852.000000   
mean       0.799265       7.287724          0.365462      0.319857   
std        0.400561       1.319733          0.206705      0.144350   
min        0.000000       3.800000          0.080000      0.000000   
25%        1.000000       6.500000          0.240000      0.260000   
50%        1.000000       7.100000          0.300000      0.320000   
75%        1.000000       7.700000          0.410000      0.400000   
max        1.000000      15.900000          1.580000      1.660000   

       residual sugar     chlorides  free sulfur dioxide  \
count    19852.000000  19852.000000         19852.000000   
mean         4.956604      0.052638            31.336591   
std          4.324208      0.039722            27.324857   
min          0.600000      0.009000             1.000000   
25%          1.800000      0.033000            16.000000   
50%          2.700000      0.042000            28.000000   
75%          7.400000      0.058000            39.000000   
max         65.800000      0.611000           289.000000   

       total sulfur dioxide       density            pH     sulphates  \
count          19852.000000  19852.000000  19852.000000  19852.000000   
mean             114.907062      0.994010      3.240772      0.514564   
std               62.240752      0.003176      0.166644      0.145950   
min                6.000000      0.987110      2.720000      0.220000   
25%               81.000000      0.991100      3.140000      0.420000   
50%              116.000000      0.993900      3.240000      0.490000   
75%              148.000000      0.996800      3.360000      0.600000   
max              440.000000      1.038980      4.010000      2.000000   

            alcohol      quality  
count  19852.000000  19852.00000  
mean      10.867175      6.00000  
std        1.350926      2.00005  
min        8.000000      3.00000  
25%        9.700000      4.00000  
50%       10.700000      6.00000  
75%       12.200000      8.00000  
max       14.900000      9.00000

In [66]:
wine["quality"].value_counts()

6    2836
5    2836
7    2836
8    2836
4    2836
3    2836
9    2836
Name: quality, dtype: int64

In [67]:
x=wine.iloc[:,0:12]
x

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0         1            7.0              0.27         0.36            20.7   
1         1            6.3              0.30         0.34             1.6   
2         1            8.1              0.28         0.40             6.9   
3         1            7.2              0.23         0.32             8.5   
4         1            7.2              0.23         0.32             8.5   
...     ...            ...               ...          ...             ...   
19847     1            6.9              0.36         0.34             4.2   
19848     1            6.6              0.36         0.29             1.6   
19849     1            7.4              0.24         0.36             2.0   
19850     1            6.6              0.36         0.29             1.6   
19851     1            6.9              0.36         0.34             4.2   

       chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0          0.045                 45.0                 170.0  1.00100  3.00   
1          0.049                 14.0                 132.0  0.99400  3.30   
2          0.050                 30.0                  97.0  0.99510  3.26   
3          0.058                 47.0                 186.0  0.99560  3.19   
4          0.058                 47.0                 186.0  0.99560  3.19   
...          ...                  ...                   ...      ...   ...   
19847      0.018                 57.0                 119.0  0.98980  3.28   
19848      0.021                 24.0                  85.0  0.98965  3.41   
19849      0.031                 27.0                 139.0  0.99055  3.28   
19850      0.021                 24.0                  85.0  0.98965  3.41   
19851      0.018                 57.0                 119.0  0.98980  3.28   

       sulphates  alcohol  
0           0.45      8.8  
1           0.49      9.5  
2           0.44     10.1  
3           0.40      9.9  
4           0.40      9.9  
...          ...      ...  
19847       0.36     12.7  
19848       0.61     12.4  
19849       0.48     12.5  
19850       0.61     12.4  
19851       0.36     12.7  

[19852 rows x 12 columns]

In [68]:
y=wine.iloc[:,-1]
y

0        6
1        6
2        6
3        6
4        6
        ..
19847    9
19848    9
19849    9
19850    9
19851    9
Name: quality, Length: 19852, dtype: int64

In [69]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=20)

In [70]:
x_train.values

array([[ 1.  ,  8.3 ,  0.21, ...,  3.02,  0.6 , 12.9 ],
       [ 1.  ,  6.1 ,  0.26, ...,  3.44,  0.64, 10.5 ],
       [ 1.  ,  6.1 ,  0.26, ...,  3.44,  0.64, 10.5 ],
       ...,
       [ 1.  ,  7.  ,  0.12, ...,  3.19,  0.38,  9.8 ],
       [ 1.  ,  7.1 ,  0.31, ...,  3.14,  0.4 ,  9.5 ],
       [ 1.  ,  6.2 ,  0.28, ...,  2.98,  0.64, 13.1 ]])

In [71]:
x_test.values

array([[ 1.  ,  5.6 ,  0.21, ...,  3.22,  0.95, 11.6 ],
       [ 1.  ,  6.2 ,  0.28, ...,  2.98,  0.64, 13.1 ],
       [ 1.  ,  9.1 ,  0.27, ...,  3.2 ,  0.46, 10.4 ],
       ...,
       [ 1.  ,  7.1 ,  0.21, ...,  3.13,  0.33,  9.9 ],
       [ 0.  ,  9.7 ,  0.53, ...,  3.3 ,  0.86, 12.4 ],
       [ 1.  ,  7.6 ,  0.26, ...,  3.15,  0.4 , 10.4 ]])

In [72]:
y_train.values

array([7, 3, 3, ..., 8, 5, 8], dtype=int64)

In [73]:
y_test.values

array([8, 8, 9, ..., 6, 6, 4], dtype=int64)

In [74]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [75]:
y_pred = classifier.predict(x_test)
y_pred

array([8, 8, 9, ..., 9, 4, 9], dtype=int64)

In [76]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
ac = accuracy_score(y_pred,y_test)*100
cm = confusion_matrix(y_pred,y_test)
cr = classification_report(y_pred,y_test)
print(ac)

35.00377738604886


In [77]:
print(cm)

[[243  50  22  26  10  18   0]
 [106 167  99  74  33  20   0]
 [ 72 112 177  82  27  24   0]
 [ 43  62  92  77  43  35   0]
 [  0  35  19  28  34  29   0]
 [ 35  71  97 119 137 127   0]
 [ 74  74  53 168 302 290 565]]


In [78]:
print(cr)

              precision    recall  f1-score   support

           3       0.42      0.66      0.52       369
           4       0.29      0.33      0.31       499
           5       0.32      0.36      0.34       494
           6       0.13      0.22      0.17       352
           7       0.06      0.23      0.09       145
           8       0.23      0.22      0.22       586
           9       1.00      0.37      0.54      1526

    accuracy                           0.35      3971
   macro avg       0.35      0.34      0.31      3971
weighted avg       0.55      0.35      0.39      3971



In [79]:
wine

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0         1            7.0              0.27         0.36            20.7   
1         1            6.3              0.30         0.34             1.6   
2         1            8.1              0.28         0.40             6.9   
3         1            7.2              0.23         0.32             8.5   
4         1            7.2              0.23         0.32             8.5   
...     ...            ...               ...          ...             ...   
19847     1            6.9              0.36         0.34             4.2   
19848     1            6.6              0.36         0.29             1.6   
19849     1            7.4              0.24         0.36             2.0   
19850     1            6.6              0.36         0.29             1.6   
19851     1            6.9              0.36         0.34             4.2   

       chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0          0.045                 45.0                 170.0  1.00100  3.00   
1          0.049                 14.0                 132.0  0.99400  3.30   
2          0.050                 30.0                  97.0  0.99510  3.26   
3          0.058                 47.0                 186.0  0.99560  3.19   
4          0.058                 47.0                 186.0  0.99560  3.19   
...          ...                  ...                   ...      ...   ...   
19847      0.018                 57.0                 119.0  0.98980  3.28   
19848      0.021                 24.0                  85.0  0.98965  3.41   
19849      0.031                 27.0                 139.0  0.99055  3.28   
19850      0.021                 24.0                  85.0  0.98965  3.41   
19851      0.018                 57.0                 119.0  0.98980  3.28   

       sulphates  alcohol  quality  
0           0.45      8.8        6  
1           0.49      9.5        6  
2           0.44     10.1        6  
3           0.40      9.9        6  
4           0.40      9.9        6  
...          ...      ...      ...  
19847       0.36     12.7        9  
19848       0.61     12.4        9  
19849       0.48     12.5        9  
19850       0.61     12.4        9  
19851       0.36     12.7        9  

[19852 rows x 13 columns]

In [80]:
x1=wine.iloc[:,1:13]
x1

fixed acidity  volatile acidity  citric acid  residual sugar  \
0                7.0              0.27         0.36            20.7   
1                6.3              0.30         0.34             1.6   
2                8.1              0.28         0.40             6.9   
3                7.2              0.23         0.32             8.5   
4                7.2              0.23         0.32             8.5   
...              ...               ...          ...             ...   
19847            6.9              0.36         0.34             4.2   
19848            6.6              0.36         0.29             1.6   
19849            7.4              0.24         0.36             2.0   
19850            6.6              0.36         0.29             1.6   
19851            6.9              0.36         0.34             4.2   

       chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0          0.045                 45.0                 170.0  1.00100  3.00   
1          0.049                 14.0                 132.0  0.99400  3.30   
2          0.050                 30.0                  97.0  0.99510  3.26   
3          0.058                 47.0                 186.0  0.99560  3.19   
4          0.058                 47.0                 186.0  0.99560  3.19   
...          ...                  ...                   ...      ...   ...   
19847      0.018                 57.0                 119.0  0.98980  3.28   
19848      0.021                 24.0                  85.0  0.98965  3.41   
19849      0.031                 27.0                 139.0  0.99055  3.28   
19850      0.021                 24.0                  85.0  0.98965  3.41   
19851      0.018                 57.0                 119.0  0.98980  3.28   

       sulphates  alcohol  quality  
0           0.45      8.8        6  
1           0.49      9.5        6  
2           0.44     10.1        6  
3           0.40      9.9        6  
4           0.40      9.9        6  
...          ...      ...      ...  
19847       0.36     12.7        9  
19848       0.61     12.4        9  
19849       0.48     12.5        9  
19850       0.61     12.4        9  
19851       0.36     12.7        9  

[19852 rows x 12 columns]

In [81]:
y1=wine.iloc[:,:1]
y1

type
0         1
1         1
2         1
3         1
4         1
...     ...
19847     1
19848     1
19849     1
19850     1
19851     1

[19852 rows x 1 columns]

In [82]:
from sklearn.model_selection import train_test_split
x1_train, x1_test, y1_train, y1_test = train_test_split(x1,y1, test_size=0.2, random_state=20)

In [83]:
x1_train.values

array([[ 8.3 ,  0.21,  0.4 , ...,  0.6 , 12.9 ,  7.  ],
       [ 6.1 ,  0.26,  0.25, ...,  0.64, 10.5 ,  3.  ],
       [ 6.1 ,  0.26,  0.25, ...,  0.64, 10.5 ,  3.  ],
       ...,
       [ 7.  ,  0.12,  0.29, ...,  0.38,  9.8 ,  8.  ],
       [ 7.1 ,  0.31,  0.25, ...,  0.4 ,  9.5 ,  5.  ],
       [ 6.2 ,  0.28,  0.28, ...,  0.64, 13.1 ,  8.  ]])

In [84]:
x1_test.values

array([[ 5.6 ,  0.21,  0.4 , ...,  0.95, 11.6 ,  8.  ],
       [ 6.2 ,  0.28,  0.28, ...,  0.64, 13.1 ,  8.  ],
       [ 9.1 ,  0.27,  0.45, ...,  0.46, 10.4 ,  9.  ],
       ...,
       [ 7.1 ,  0.21,  0.3 , ...,  0.33,  9.9 ,  6.  ],
       [ 9.7 ,  0.53,  0.6 , ...,  0.86, 12.4 ,  6.  ],
       [ 7.6 ,  0.26,  0.36, ...,  0.4 , 10.4 ,  4.  ]])

In [85]:
y1_train.values

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [86]:
y1_test.values

array([[1],
       [1],
       [1],
       ...,
       [1],
       [0],
       [1]], dtype=int64)

In [87]:
from sklearn.naive_bayes import GaussianNB
classifier_1 = GaussianNB()
classifier_1.fit(x1_train,y1_train)

C:\Users\Kajal\anaconda3\lib\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [88]:
y1_pred = classifier_1.predict(x_test)
y1_pred

C:\Users\Kajal\anaconda3\lib\site-packages\sklearn\base.py:488: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- type
Feature names seen at fit time, yet now missing:
- quality

  warnings.warn(message, FutureWarning)


array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [89]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
ac1 = accuracy_score(y1_pred,y1_test)*100
cm1 = confusion_matrix(y1_pred,y1_test)
cr1 = classification_report(y1_pred,y1_test)
print(ac1)

80.73533115084362


C:\Users\Kajal\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Kajal\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Kajal\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [90]:
print(cm1)

[[   0    0]
 [ 765 3206]]


In [91]:
print(cr1)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.81      0.89      3971

    accuracy                           0.81      3971
   macro avg       0.50      0.40      0.45      3971
weighted avg       1.00      0.81      0.89      3971

